// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi48dVvQrqAUWav2CFCJHN7jbu5fXEpFE',
    appId: '1:830137891866:web:1cefeaaec94df53a70e5a3',
    messagingSenderId: '830137891866',
    projectId: 'food-delivery-9cdd3',
    authDomain: 'food-delivery-9cdd3.firebaseapp.com',
    storageBucket: 'food-delivery-9cdd3.appspot.com',
    measurementId: 'G-4KCWCS5PC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlBzkiyhFh8vcE7IVY3zjcBwydUqDuPvU',
    appId: '1:830137891866:android:357c4b71a4f9d3e570e5a3',
    messagingSenderId: '830137891866',
    projectId: 'food-delivery-9cdd3',
    storageBucket: 'food-delivery-9cdd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIQOwB_mvDCiE9hd6SNqU0G2qQfRxJRu4',
    appId: '1:830137891866:ios:36e432dce7ce337770e5a3',
    messagingSenderId: '830137891866',
    projectId: 'food-delivery-9cdd3',
    storageBucket: 'food-delivery-9cdd3.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
